README.md
=> docs: readme수정

.gitmessage.txt, src/components/common/Header.tsx
1.  git commit message 설정
.gitmessage.txt 파일 추가했습니다.
본문/푸터는 선택사항이고, 간단한 스타일 수정이나 마크업 정도는 제목만 작성해주세요
동일하게 git add [파일명 또는 .] + enter 후에, git commit + enter 하시면 템플릿이 나옵니다.
이 때, i 를 누르시면 insert 모드로 변환되고, 맨앞에 # 이 붙지 않은 라인의 내용만 commit 내용으로 올라옵니다.
입력이 끝나면 ESC 누르시고 :wq + enter 하시면 커밋이 완료됩니다.
close #14
=> my commit message template

src/components/routes/SignUp.tsx
- 어떤 내용을 작업했는지 간략하게 작성해주세요.
*비밀번호 보여지는 아이콘 
1. 처음 아이콘 기본값 FaRegEyeSlash (Input type=password 비밀번호 보호 )
2. FaRegEyeSlash 클릭 시-> FaRegEye로 변경  Input type=text타입으로 비밀번호 보여짐
3. FaRegEye -> 클릭 시 -> FaRegEyeSlash로 변경 -> Input type=password타입으로 비밀번호 보호
*이메일 중복확인 기능 구현
1. 이메일이 중복 먼저 확인하고 이메일 중복이면 "이메일이 중복되었습니다" alert창
2. 이메일이 중복되지 않으면 확인 버튼 후
3. 인증 코드 발송 됐다는 alert창
- 비밀번호 가시성 기능구현은 했습니다 혹시 아이콘 마음에 드시나요? 
-코드 기능 구현은 했는데 서버가 아직 없어서 중복확인을 할 수 없네요ㅜㅜ
close # 20
=> 회원가입 비밀번호 가시성 기능구현, 이메일 중복확인 기능 구#20

src/components/routes/Login.tsx
1. 로그인 폼 구현 (이메일, 비밀번호, 로그인버튼, 이메일찾기버튼)
2. 비밀번호 가시성 구현(눈 아이콘)
3.  정보를 입력하지 않으면 "정보를 입력하지 않았습니다"라는 alert 구현
4. 모든 정보를 입력하면 "로그인 완료되었습니다"라는 alert 구현
5. 서버 API axios로 구현 (API없어서 주석처리) 
6. "이메일 찾기" 버튼 누르면 FindEmail로 이동하는 코드 구현
- 디자인적 요소나 더 필요한 기능 구현이 있을지 봐주세요!
- 예원님이 말씀해주신대로 axios로 기능 구현해서 주석처리 해놨습니다!
close #22
=> feat : 로그인 기능

src/components/routes/FindEmail.tsx, src/components/routes/SignUp.tsx
1. 이메일 찾기 폼 구현, style 완성
2. 모든 정보를 입력하지 않고 "이메일 찾기"버튼을 누르면 "정보를 입력해주세요" alert 구현
3. 모든 정보를 입력해서 "이메일 찾기"버튼을 클릭하면 이메일과 이메일 찾기 성공 모달창 구현
4. 이메일 찾기 API 구현 ->  API가 없어서 기능 로직만 구현하고 주석처리
5. 휴대폰 번호 형식 "( - 사용)" 추가 (회원가입-휴대폰번호,회사번화번호/이메일찾기-휴대폰번호)
6. "회사는 이메일 찾기를 지원하지않습니다" 문구 추가
- 모달창은 만들었는데  API가 아직 없어서 캡쳐가 안되네여ㅜㅜ 미리 캡쳐 해놨어야하는데 죄송합니다ㅜㅜ
- 이메일 찾기 기능에서 더 필요한 기능이 있을까 봐주세요! 제 생각에는 충분하다고 생각합니다
close #26
=> 이메일 찾기/#26

src/components/axios/http.ts, src/components/axios/instances.ts, src/components/routes/CreateJobPost.tsx, src/components/type/jobPosting.ts
1. 인스턴스 작업을 하였습니다. 추후 토큰 헤더에 추가하는 작업을 하면 됩니다.
2. use에서 에러를 인터셉터하여 반환해주었습니다.
3. 채용공고 post 요청을 위한 data 형식 맞추었습니다.
4. type 폴더 만들었습니당
이해 안되는 부분 있으면 말씀해주세요.
close #28
=> feat: axios 인스턴스 작업 및 채용공고 생성 api 연동

src/App.tsx, src/Router.tsx, src/components/css/ScheduleFormStyle.ts, src/components/routes/FormAssignment.tsx, src/components/routes/FormInterview.tsx, src/components/routes/Modal.tsx, src/components/routes/RecruitBoard.tsx
1 .채용단계 모달창 UI 구현(date-picker 부분 제외)
2. 모달창 열기/닫기 가능
3. 뒷 배경 블러처리
4. 과제/면접 전형 Outlet으로 구분하여 탭 이동 가능
5. [다음]버튼 누르면 내용이 옆으로 넘겨지면서 예약 메일 form 으로 이동(예정)
버튼들 컬러가 괜찮나 모르겠네요 :) 의견 환영입니다 !
date-picker는 공통으로 빼주시면 작업하려고 빼고 작업했습니다
close #39
=> 채용단계 모달창 UI 구현(date-picker 부분 제외)

src/components/axios/http/user.ts, src/components/routes/Login.tsx, src/components/routes/SignUp.tsx, src/components/type/user.ts
1. 로그인 api post 요청 및 타입 지정
아직 전역상태 안했습니다. 회원가입 연동하면 진행하겠습니다
close #43
=> 로그인 api post 요청 및 타입 지정

src/components/axios/http/user.ts, src/components/routes/SignUp.tsx
1. Promise 함수 axios로 변경
2. handleSubmit 함수에서 회원가입 company, candidate 나눠서 post 요청
- API연결 하고 머지해야할까요?
close # 48
=> Edit : 회원가입 피드백 수정

src/components/axios/http/user.ts, src/components/routes/SignUp.tsx
1. 이메일 중복/ 이메일 인증코드 코드 수정
- Proxy 사용해서 다시 해보겠습니다
- CORS 설정으로 인한 Error
close #
=> Edit : 이메일 중복/ 이메일 인증코드

src/components/axios/http/user.ts, src/components/axios/instances.ts, src/components/routes/SignUp.tsx, vite.config.ts
1. 회원가입  API 연결
- 이메일 중복 확인이 안됨 
close #58
=> feat: 회원가입 API 연결

src/components/axios/instances.ts, vite.config.ts
proxy 설정 변경 및 주석 정리
proxy 오류나는 이유 발견! 
수정은 했으나 백엔드에서 이미 CORS 설정을 해주셔서 마찬가지로 주석처리 해두겠습니당 ㅎㅎ
close #60
=> proxy 설정 변경 및 주석 정리

src/components/axios/http/jobPosting.ts, src/components/input/Checkbox.tsx, src/components/input/SelectInput.tsx, src/components/routes/CreateJobPost.tsx, src/components/routes/JobPostDetail.tsx
1. 디테일에서 수정 정보 넘기기
2. state가 있으면 수정하기 기능으로 판단
3. 수정모드일 경우 수정불가능한 input 없애기
4. 정보를 기본 input에 넣어놓기
예원님이 하신것처럼 editMode 에 따라 변화를 주었습니다.
KEY나 API 연동은 서버완성되면 하면서 자잘한 이슈들 해결하려구요ㅠ
close #36
=> 채용공고 수정하기 기능

src/components/common/Header.tsx, src/components/routes/Index.tsx, src/components/routes/Login.tsx, src/recoil/atoms/userAtom.ts, src/recoil/store.ts
1. user정보 Recoil로 저장 및 디렉토리 생성
2. src > recoil > atoms / selectors / store.ts 생성
3. atoms 폴더에는 atom 만 저장
4. atom 관련해서 가공한 데이터가 필요하시면 selectors 폴더에 파일 만들어서 작성해주세요
5. store.ts는 디렉토리 구조를 위해 전체 atom과 selector를 한 곳에 모으는 역할입니다
6. 메인페이지 경고문구는 시험삼아 적용해놨습니다
7. Header 로그인/회원가입 버튼 분리하고 권한에따라 버튼 종류 및 경로 변경했습니다
저희는 recoil 함수를 useRecoilState / useRecoilValue / useSetRecoilState 밖에 안쓸 것같아서 
적용은 어렵지 않을 거라 생각됩니당 
폴더구조 같은게 혹시 이해안되시면 말씀해주세용
참고로 모든 atom / selector 생성시 store.ts에 export 해주시고
다른 페이지에서 가져다 쓰실 때, store.ts 에 있는 atom / selector 사용하는걸로 통일해주세요 !
close #65
=> user정보 Recoil로 저장 및 디렉토리 생성

src/components/axios/http/jobPosting.ts, src/components/routes/CreateJobPost.tsx, src/enum/options.ts
1. 채용공고 input에 빈값이 있으면 아예 비활성화 시켰습니다.
2. select option들을 enum 폴더로 옮겼습니다.
유나님 이력서보기에도 option들 enum에서 가져다 간단하게 쓸 수 있습니다!
close #66
=> 채용공고 빈값 검사

package-lock.json, package.json, src/components/axios/http/jobPosting.ts, src/components/css/input.ts, src/components/input/DatePickerDuration.tsx, src/components/input/DatePickerOne.tsx, src/components/input/SelectInput.tsx, src/components/input/TimePicker.tsx, src/components/routes/CreateJobPost.tsx, src/enum/options.ts
1. 아래 스크린샷과 같이 클릭하면 드롭다운으로 선택할 수 있도록 했습니다. 기존 사용하던 곳에 문제가 되지 않도록 높이를 맞추다보니 원래 있던 자리를 클릭할 수 있도록 했습니다.
2. locale 한국 기준으로 설정을 했습니다. 월이 숫자로 표시됩니다.
locale을 위해서 date-fns, date-fns-tz 를 다운받았습니다.
pull 이후에 npm install을 해주세요.
close #71
=> DataPicker 년과 월을 선택할 수 있도록 구현

src/components/routes/CreateResume.tsx, src/components/routes/ViewResume.tsx
1. 학교명 input생성
2. datepicker 생성 (날짜선택 전 오늘날짜로 보여짐)
3. 희망직무. 최종학력 공통input으로 변경
4. 이미지첨부 기능구현
5. 이미지 첨부된 상태에서 이미지를 클릭하면 다시 파일 첨부가 떠서 이미지 변경 가능
6. 포트폴리오 파일 업로드시 "파일삭제" 버튼과 기능 구현
- 처음 input 클릭 후 사진 선택하면 이미지가 변경되지 않고 다시 파일 첨부가 2번 뜬다..
close #67
=> 이력서 datePicker 생성, 학교명 생성, 기능 추가/#67

src/axios/http/user.ts, src/pages/FindEmail.tsx, src/pages/Index.tsx, src/pages/SignUp.tsx
1. 이메일 찾기 API 연결
- API가 다시 연결 되면 다시 수정하겠습니다 
- 일단 코드 구현만 해놨습니다 
- Failed to load resource: the server responded with a status of 403 ()
-  config 파일에서 api 주소가 빠져있다고 하심
close #76
=> 이메일 찾기 API 연결/#76

src/axios/http/user.ts, src/pages/Account.tsx, src/pages/Login.tsx, src/pages/Modal.tsx
1. 어떤 내용을 작업했는지 간략하게 작성해주세요.
close #
=> 비밀번호 변경, 회원탈퇴 API 연결/#80

src/axios/http/user.ts, src/pages/Account.tsx, src/pages/SignUp.tsx
1. 어떤 내용을 작업했는지 간략하게 작성해주세요.
close #
=> 회원탈퇴 API 연결

src/assets/style/GlobalStyles.ts, src/axios/http/interview.ts, src/pages/Modal.tsx, src/pages/RecruitBoard.tsx, src/type/recruitBoard.ts
1.일정삭제 기능
2. 지원자 이동 기능
일정 삭제 API가 미완성이라 테스트는 못해봤습니다
param을 아직 못받아와서 다음 PR에 수정해두겠습니다
지원자 클릭으로 넘기기는 했는데 드래그 앤 드롭은 라이브러리를 써야해서 브랜치를 나누겠습니당
탈락된 지원자들은 어떻게 처리할까요? 
일단 담아두기는 했는데 필요 없으면 지우겠습니다! 
남아있게되면 클릭/드래그 비활성화 해야할 것 같네요
close #85
=> [채용단계] 일정삭제 기능 및 지원자 이동 기능

src/axios/http/jobPosting.ts, src/components/input/SelectInput.tsx, src/constants/options.ts, src/pages/CreateJobPost.tsx, src/pages/Index.tsx, src/pages/JobPostDetail.tsx, src/route/Router.tsx, src/type/jobPosting.ts
1. 파일 보내기 해결했습니다.
2. 전체 공고 1page만 불러오도록 임시로 해놓았습니다.
3. 디테일에서 api 불일치로 나는 오류들을 해결하였습니다.
돌아만 가게해서 자세한 타입 에러같은건 천천히 해결해보겠습니다,,,
close #89
=> feat: 생성 파일업로드 및 불러오기 오류 해결

src/axios/http/user.ts, src/axios/instances.ts, src/pages/Account.tsx
1. 비밀번호 변경 API 연결 완료
2. 회원탈퇴 API 연결  완료
close #80
=> 비밀번호 변경, 회원탈퇴 API 연결 최종확인 완료/#80

src/pages/CreateResume.tsx, src/pages/ViewResume.tsx
1. 이력서 삭제 API 로직 구현
2. 이력서 조회 API 로직 구현
close #
=> 이력서 삭제, 조회 API 로직 구현/#84

src/axios/http/jobPosting.ts, src/pages/CompanyMypage.tsx, src/pages/RecruitBoard.tsx, src/type/company.ts
1. 원래 면접일정 브랜치였는데 회사정보 API가 확정이라 먼저했습니다
2. 회사정보 GET/POST/PUT 잘 작동되었고, 삭제기능은 따로 안넣었습니
설립년도를 Date 타입으로 넘겼더니 계속 400번대 에러가 나서, string으로 넘기니까 잘 작동합니당
혹시 form 데이터 넘기실때 에러나면 타입도 확인해보세요 !
close #93
=> 회사정보 API 테스트 및 로직 수정

src/axios/http/interview.ts, src/axios/http/recruitBoard.ts, src/pages/CompanyMypage.tsx, src/pages/Modal.tsx, src/pages/RecruitBoard.tsx
1. 일정 삭제 API 확정 및 자잘한 수정
일정 관련 API를 전체적으로 수정하기로했어요,,
바뀐건 별로 없지만 일정 삭제  API는 확정해서 적용했습니당
close #92
=> 일정 삭제 API 확정 및 자잘한 수정

package-lock.json, package.json, src/axios/http/jobPosting.ts, src/axios/instances.ts, src/components/common/Header.tsx, src/constants/Time.ts, src/constants/options.ts, src/pages/CompanyMypage.tsx, src/pages/CreateJobPost.tsx, src/pages/JobPostDetail.tsx, src/pages/Login.tsx, src/recoil/atoms/userAtom.ts, src/type/jobPosting.ts, src/type/user.ts
1. 유저정보 persist로 저장했습니당
이번엔 오류가 없겠죠...?
2. 1시간 지나면 토큰을 삭제해야함
저장할 때 만료시간을 함께 저장
request 할 때 지나면 삭제
3. 헤더에서 토큰이 없으면 authUserState삭제
request 할 때 localStorage를 직접 건드려서 했지만, recoil에서 바뀌었는지 감지를 못해서 실제 데이터와 싱크가 안맞는다.
따라서 모든 화면에 있는 헤더에서 토큰이 없으면 null로 해줌
4. 채용공고 오류 수정
예원님이 말씀해주신 0 오류수정했습니다
디테일에서 회사정보 없으면 (0이나 날짜없을때도) 비어있게 수정했습니다.
이번엔 오류가 없겠죠...?
recoil-persist 다운로드로 이해 npm install 이 필요함니다.
close #97
=> 유저정보 persist로 저장, 토큰 저장, 채용공고 0 오류 수정

src/constants/options.ts
hotfix: 직무, 학력 value enum영어로 수정
급해서 바로 머지합니다
close #101
=> hotfix: 직무, 학력 value enum영어로 수정

src/assets/style/MypageStyle.ts, src/pages/CompanyMypage.tsx, src/route/Router.tsx, src/type/company.ts
1. 채용공고 목록 API 불러오기
2. 데이터 타입 명세서랑 맞춰서 수정
3. 채용단계로 key 전달
D-day 앞에 색깔 변경을 안넣었군뇨,, 나중에 추가로 넣겠습니다 ㅎ
경력은 0이면 신입, 그 이상이면 "년 이상"이 붙도록 했습니
close #103
=> 채용공고 목록 API 및 채용단계로 key전달

src/pages/ProtectedRoute.tsx
1. ProtectedRoute 구현
이제 ProectedRoute로 감싸진 라우트들은 로그인 전에 접근할 수 없습니당
close #108
=> ProtectedRoute 구현

src/axios/http/candidate.ts, src/axios/http/resume.ts, src/pages/UserMypage.tsx, src/type/candidate.ts, src/type/resume.ts
1. 응시자 마이페이지 API 연동
2. API 함수 바꾸고 응답 type이랑 body type 지정해뒀습니당
3. user 정보에는 핸드폰번호가 안와서 뺐습니다
아직 이력서쪽 오류가 나신다고해서 테스트가 안되는 것 같습니다
이력서 생성이 안되어서 지원한 공고목록도 확인은 못하고 구현만 해두었습니당
혹시 body 타입 안맞으면 말씀해주세요 !
close #112
=> 응시자 마이페이지 API

src/assets/style/input.ts, src/axios/http/jobPosting.ts, src/components/input/Checkbox.tsx, src/components/input/DatePickerDuration.tsx, src/constants/options.ts, src/main.tsx, src/pages/CreateJobPost.tsx, src/pages/Index.tsx, src/pages/JobPostDetail.tsx, src/route/Router.tsx, src/type/company.ts, src/type/jobPosting.ts, src/utils/Format.ts
1. 메인페이지 무한스크롤
2. 채용공고 수정하기를 마무리했습니다.
3. 채용공고에서 타입 에러 나던 코드를 고쳤습니다.
무한스크롤에서 왜 두번 호출될까요..
close #114
=> 무한스크롤, 채용공고 수정하기

src/axios/http/resume.ts
1. 어떤 내용을 작업했는지 간략하게 작성해주세요.
close #
=> resume.ts 로직 최최종

src/axios/http/resume.ts, src/pages/RecruitBoard.tsx, src/pages/UserMypage.tsx
1. resume.ts 복구 및 이력서 상태 수정
close #124
=> resume.ts 복구 및 이력서 상태 수정

src/axios/http/jobPosting.ts, src/pages/Index.tsx, src/pages/JobPostDetail.tsx
1. 채용공고 삭제기능
2. 메인 이력서나 정보가 있는지 여부에 따라 메세지
3. 지원하기할 때 message를 alert
close #129
=> feat: 채용공고 삭제 및 메인 안내메시지 조건

src/axios/instances.ts, src/pages/CreateResume.tsx, src/pages/ViewResume.tsx
=> 이력서 Error 해결

src/pages/CompanyMypage.tsx
1. companyMypago.tsx </> 추가
close #135
=> hotfix: 괄호 닫힘 오류

src/pages/FindEmail.tsx, src/pages/Login.tsx, src/pages/SignUp.tsx, src/pages/ViewResume.tsx
1. 회원가입, 로그인, 이메일찾기 버튼 UI 수정
2. 이력서 수정, 삭제 권한 설정
close #137
=> 전체적인 UI 수정/ 디테일 기능 추가#137

src/axios/fetch/recruitBoard.ts, src/components/FormContent.tsx, src/components/Modal.tsx, src/pages/RecruitBoard.tsx
1. 단계 넘어가는 로직이 계속 오류나서 아예 api를 refetch하기로 했습니다
2. 일정 생성 등의 동작을 할때마다 지원자들 정보가 refetch 되어야 해서 아예 ReactQuery로 만들었습니다
3. error 타입이 unknown이라 message 추출이 안되길래 타입가드 해줬습니다
ReactQuery를 쓰니까 이렇게 간편히 refetch가 가능한 것을....
기나긴 로직으로 한참 돌았네요
error 타입가드 필요하시면 참고하세용
저는 빨간줄 그어진 곳들 없애러 갑니다~~
close #138
=> 찐찐 최종 채용단계 디버깅 및 ReactQuery 적용

src/axios/http/interview.ts, src/axios/instances.ts, src/pages/Account.tsx, src/pages/CreateJobPost.tsx, src/pages/FindEmail.tsx, src/pages/Index.tsx, src/pages/JobPostDetail.tsx, src/pages/Login.tsx, src/pages/RecruitBoard.tsx, src/pages/SignUp.tsx, src/pages/ViewResume.tsx, src/type/candidate.ts, src/type/interview.ts
1. 타입에러 및 자잘한 이슈 정리
close #141
=> 타입에러 및 자잘한 이슈 정리

.gitignore, src/axios/http/interview.ts, src/axios/instances.ts, src/pages/Account.tsx, src/pages/CreateJobPost.tsx, src/pages/FindEmail.tsx, src/pages/Index.tsx, src/pages/JobPostDetail.tsx, src/pages/Login.tsx, src/pages/RecruitBoard.tsx, src/pages/SignUp.tsx, src/pages/ViewResume.tsx, src/type/candidate.ts, src/type/interview.ts
1. .vscode 폴더 및 .env 파일 생성/환경변수 적용
.vscode는 처음에 생성했어야하는데 ㅎㅎ .. 제 vscode 설정에 맞췄습니다
env에는 base_url만 담았어요
close #143
=> .vscode 폴더 및 .env 파일 생성/환경변수 적용

src/axios/http/resume.ts, src/components/common/Header.tsx, src/components/input/SelectInput.tsx, src/pages/Account.tsx, src/pages/CreateResume.tsx, src/pages/Index.tsx, src/pages/SignUp.tsx, src/pages/ViewResume.tsx, src/type/resume.ts, src/utils/Format.ts
=> fix: 타입에러 수정

vite.json
=> feat: vite.json 추가

vite.json
hotifx: vite.json index.html 추가
=> hotifx: vite.json 추가

index.html
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` 추가
https://m.blog.naver.com/kairosys/222856947047
=> hotfix: meta태그에 추가해서  mixed content 해결

api/handler.ts, package-lock.json, package.json, vercel.json
1. 배포 오류 수정 시도
mixed contents 오류
close #152
=> fix: 배포 오류 수정 시도

index.html
=> hotfix: 메타태그 삭제

index.html, vercel.json
1. vercel.json api 삭제
2. meta태그삭제
=> hotfix: vercel.json api 삭제 meta태그삭제

src/pages/Account.tsx, src/pages/Index.tsx, src/pages/JobPostDetail.tsx, src/pages/Login.tsx, src/pages/SignUp.tsx
1. 비밀번호 안내문구 변경
2. 전체적인 스타일 수정
3. 탈퇴시 로그아웃 안되는 부분 수정
스타일은 인풋창 넓이가 글씨따라 변하는거 고정하고
border-radius랑 간격, 글자 크기 등 수정했습니다
글자 크기는 기본 16px이고, 안내문구는 14px정도가 적당해요
정말 최소한의 크기는 12px입니다 10px은 브라우저가 인식을 잘 못해서 깨져요!
보기에 힘든 사이즈이기도 해서 수정했습니다
close #155
=> 1,2,10 안내문구 수정 및 스타일 변경

src/pages/Account.tsx, src/pages/CreateJobPost.tsx, src/pages/CreateResume.tsx
1. 비밀번호 변경 문구 에러 수정
2. 이미지 파일 들어가는 곳 "이미지 업로드 시 "jpg", "jpeg", "png" 만 가능  , 최대 허용 크기 10MB" 문구 넣어줌
close #160
=> 테스트 에러 8번 10번 수정/#160

src/pages/JobPostDetail.tsx
1. 회사 홈페이지 https가 안붙어있으면 붙여서 링크 연결
close #163
=> 회사 홈페이지 https로 링크 연결

src/pages/CreateJobPost.tsx, src/pages/CreateResume.tsx, src/pages/ViewResume.tsx
1. 정책 변경으로 이력서 삭제기능을 삭제함
close #166
=> 이력서 삭제기능을 삭제

src/pages/CreateResume.tsx
=> 포트폴리오 확장자 문구 삭제

src/pages/JobPostDetail.tsx
1. 채용공고 줄바꿈 
2. 기술스택 하나만 있으면 쉼표 없도록
close #170
=> 채용공고 줄바꿈 및 기술스택 리팩토링

src/pages/Index.tsx
1. 로그아웃 해도 문구가 남아있는 버그 해결
close #175
=> 로그아웃 해도 문구가 남아있는 버그 해결

src/pages/Index.tsx
=> 권한에 따른 안내문구 재수정

README.md
1. 어떤 내용을 작업했는지 간략하게 작성해주세요.
close #
=> README 최최종 수정

robots.txt
=> seo: robots update

src/assets/style/GlobalStyles.ts, src/pages/Index.tsx
1. 회색 진하게 변경
2. color-red색 진하게 변경
close #197
=> fix: 접근성 색 대비 높이기

src/assets/style/GlobalStyles.ts, src/axios/fetch/main.ts, src/pages/Index.tsx
1.  performance 개선 시도
2. 가장 큰 컨텐으를 바꿔보려고 채용공고 제목 추가
3. 채용공고 제목 사이즈는 살짝 줄임
close #198
=>  performance 개선 시도

index.html
1. 폰트 preload 로 FOUT 개선
close #203
=> 폰트 preload 로 FOUT 개선

index.html
1. API 도메인 preconnect
close #205
=> 리소스 preconnect

index.html
1. preload 삭제 후 성능 테스트
close #205
=> preload 삭제 후 성능 테스트

db.json, routes.json, src/axios/fetch/recruitBoard.ts, src/axios/http/recruitBoard.ts, src/pages/CreateResume.tsx, src/type/recruitBoard.ts
1. db.json 업데이트 및 RecruitBoard 데이터 타입 수정
close #216
=> feat: db.json 업데이트 및 타입 수정
